######################## default configuration ####################
baseURL = "https://www.iscm.ueh.edu.vn/"
title = "Institute of Smart City & Management"



#theme = "iscmueh.github.io"
#themesDir = ".."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "iscmueh" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logoiscm.png"
# Meta data
description = "Institute of Smart City and Management, University of Economics Ho Chi Minh"
author = "ISCM"
# contact info
address = "232/6 Vo Thi Sau Str, D.3, Ho Chi Minh City"
mobile = "+84-28-3930-9589/ +84-28-3930-9269"
email = "iscm@ueh.edu.vn"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

bg = "images/banner-1.jpg"
ueh_logo = "images/ueh-logo.png"
ueh_ctd_logo = "images/ueh-logo-std.png"
ueh_address = "59C Nguyen Dinh Chieu Str, D.3, Ho Chi Minh City"
ueh_mobile = "+84-28-3829-5299/ +84-28-3829-5299"
ueh_email = "info@ueh.edu.vn"
ueh_link_recruit = "images/footer/recruitment.png"
ueh_link_future = "images/footer/buildings.png"
ueh_link_global = "images/footer/global.png"
ueh_link_elearning = "images/footer/elearning.png"
ueh_link_job = "images/footer/job.png"
ueh_link_information = "images/footer/information.png"
ueh_link_virtual = "images/footer/virtual.png"


recruitURL = "https://tuyensinh.ueh.edu.vn/"
futureURL = "https://future.ueh.edu.vn/"
globalURL = "https://global.ueh.edu.vn/"
elearningURL = "https://lms.ueh.edu.vn/"
jobURL = "https://vieclam.ueh.edu.vn/"
informationURL = "https://www.ueh.edu.vn/truyen-thong/thong-tin/"
virtualURL = "https://virtualtour.ueh.edu.vn/"



# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "10.782734"
map_longitude = "106.685605"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/ISCM.UEH"

# [[params.social]]
# title = "twitter"
# icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# title = "instagram"
# icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
# link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/iscmueh"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/iscm-ueh"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 by [ISCM](https://iscm.ueh.edu.vn)"


################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 1

[[Languages.en.menu.main]]
name = "News & Events"
url = "event"
weight = 2

[[Languages.en.menu.main]]
name = "Education"
url = "course"
weight = 3
  [[Languages.en.menu.main]]
  parent= "Education"
  weight = 1
  name="Short Course"
  url="course_shortcourse"

  [[Languages.en.menu.main]]
  parent= "Education"
  weight = 2
  name="Undergraduate"
  url="course_undergraduate"

  [[Languages.en.menu.main]]
  parent="Education"
  weight = 3
  name="Graduate"
  url="course_graduate"

[[Languages.en.menu.main]]
name = "R&D"
url = "research"
weight = 4
hasChildren = true

  [[Languages.en.menu.main]]
  parent ="R&D"
  name = "Research"
  url = "research"
  weight = 1

  [[Languages.en.menu.main]]
  parent ="R&D"
  name = "Competition"
  url = "competition"
  weight = 2

  [[Languages.en.menu.main]]
  parent ="R&D"
  name = "Other activities"
  url = "activities"
  weight = 2


#[[Languages.en.menu.main]]
#name = "blog"
#url = "blog"
#weight = 4
[[Languages.en.menu.main]]
name = "StudioLAB"
url = "studiolab"
weight = 5


[[Languages.en.menu.main]]
weight = 6
name = "People"
hasChildren = true
#url = "team"
   [[Languages.en.menu.main]]
   parent = "People"
   weight = 1
   name = "Advisory Board"
   url = "advisory"

#   [[Languages.en.menu.main]]
#   parent = "People"
#   weight = 2
#   name = "Leaders"
#   url = "leaders"


   [[Languages.en.menu.main]]
   parent = "People"
   weight = 2
   name = "Members"
   url = "members"

   [[Languages.en.menu.main]]
   parent = "People"
   weight = 3
   name = "Adjunct Professors"
   url = "adjunctprofessors"


#   [[Languages.en.menu.main]]
#   parent = "People"
#   weight = 4
#   name = "Network"
#   url = "network"



[[Languages.en.menu.main]]
weight = 8
name = "Others"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Others"
  weight = 1
  name = "notice"
  url = "notice"

  [[Languages.en.menu.main]]
  parent = "Others"
  weight = 2
  name = "Consultancy"
  url = "consultancy"

  [[Languages.en.menu.main]]
  parent = "Others"
  weight = 3
  name = "scholarship"
  url = "scholarship"

  [[Languages.en.menu.main]]
  parent = "Others"
  weight = 4
  name = "Partner"
  url = "partner"


#  [[Languages.en.menu.main]]
#  parent = "Others"
#  weight = 4
#  name = "Library"
#  url = "library"

  [[Languages.en.menu.main]]
  parent = "Others"
  weight = 5
  name = "Recruitment"
  url = "https://iscm.notion.site/Job-Board-96512d630e1642698e921c64714594a6"

#[[Languages.en.menu.main]]
#weight = 7
#name = "Admission"
#hasChildren = true
#url = "team"
#   [[Languages.en.menu.main]]
#   parent = "Admission"
#   weight = 1
#   name = "For Undergraduate"
#   url = "admission_undergraduate"


#   [[Languages.en.menu.main]]
#   parent = "Admission"
#   weight = 2
#   name = "For Graduate"
#   url = "admission_master"

#   [[Languages.en.menu.main]]
#   parent = "Admission"
#   weight = 3
#   name = "Announcement"
#   url = "admission_announcement"


[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 8


# footer menu

[[Languages.en.menu.footer]]
name = "team"
url = "team"

[[Languages.en.menu.footer]]
name = "notice"
url = "notice"

[[Languages.en.menu.footer]]
name = "event"
url = "event"

[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.en.menu.footer]]
name = "research"
url = "research"



################################### French language #####################################
[Languages.vi]
languageName = "Vi"
languageCode = "vi-vi"
contentDir = "content/vietnam"
weight = 2
home = "Trang Chủ"
# copyright
copyright = "Bản Quyền của [ISCM](https://iscm.ueh.edu.vn) 2021"



################### French navigation ####################

# main menu
[[Languages.vi.menu.main]]
name = "Giới Thiệu"
url = "about"
weight = 1

[[Languages.vi.menu.main]]
name = "Tin & Sự Kiện"
url = "event"
weight = 2

[[Languages.vi.menu.main]]
name = "Giáo Dục"
url = "course"
weight = 3
  [[Languages.vi.menu.main]]
  parent= "Giáo Dục"
  weight=2
  name="Khóa Học Ngắn Hạn"
  url="course_shortcourse"

  [[Languages.vi.menu.main]]
  parent= "Giáo Dục"
  weight=2
  name="Đại Học"
  url="course_undergraduate"

  [[Languages.vi.menu.main]]
  parent="Giáo Dục"
  weight=3
  name="Cao Học"
  url="course_graduate"

[[Languages.vi.menu.main]]
name = "R&D"
url = "research"
weight = 4

  [[Languages.vi.menu.main]]
  parent ="R&D"
  name = "Nghiên Cứu"
  url = "research"
  weight = 1

  [[Languages.vi.menu.main]]
  parent ="R&D"
  name = "Cuộc thi"
  url = "competition"
  weight = 2

  [[Languages.vi.menu.main]]
  parent ="R&D"
  name = "Các hoạt động khác"
  url = "activities"
  weight = 3


[[Languages.vi.menu.main]]
name = "StudioLAB"
url = "vi/studiolab"
weight = 5

[[Languages.vi.menu.main]]
weight = 6
name = "Nhân Sự"
#url = "resources"
hasChildren = true

  [[Languages.vi.menu.main]]
  parent = "Nhân Sự"
  weight = 1
  name = "Ban Cố Vấn"
  url = "advisory"

  #
  # [[Languages.vi.menu.main]]
  # parent = "Nhân Sự"
  # weight = 2
  # name = "Lãnh Đạo"
  # url = "leaders"
  #

  [[Languages.vi.menu.main]]
  parent = "Nhân Sự"
  weight = 2
  name = "Thành Viên"
  url = "members"

  [[Languages.vi.menu.main]]
  parent = "Nhân Sự"
  weight = 3
  name = "Adjunct Professors"
  url = "adjunctprofessors"



#  [[Languages.vi.menu.main]]
#  parent = "Nhân Sự"
#  weight = 4
#  name = "Mạng Lưới"
#  url = "network"
# [[Languages.vi.menu.main]]
# weight = 7
# name = "Tuyển Sinh"
# hasChildren = true
#   [[Languages.vn.menu.main]]
#   parent = "Tuyển Sinh"
#   weight = 1
#   name = "Đối Với Đai Học"
#   url = "admission_undergraduate"

#   [[Languages.vn.menu.main]]
#   parent = "Tuyển Sinh"
#   weight = 2
#   name = "Đối Với Cao Học"
#   url = "admission_master"

#   [[Languages.vn.menu.main]]
#   parent = "Tuyển Sinh"
#   weight = 3
#   name = "Thông Báo Tuyển Sinh"
#   url = "admission_announcement"


#[[Languages.vi.menu.main]]
#weight=7
#name="Tuyển Sinh"
#hasChildren =true
#  [[Languages.vi.menu.main]]
#  parent="Tuyển Sinh"
#  weight = 2
#  name="Cho Cao Học"
#  url="admission_master"

#  [[Languages.vi.menu.main]]
#  parent="Tuyển Sinh"
#  weight = 1
#  name="Cho Đại Học"
#  url="admission_undergraduate"
  
#  [[Languages.vi.menu.main]]
#  parent="Tuyển Sinh"
#  weight = 3
#  name="Thông Báo Tuyển Sinh"
#  url="admission_announcement"

[[Languages.vi.menu.main]]
weight = 8
name = "Khác"
hasChildren = true


  [[Languages.vi.menu.main]]
  parent = "Khác"
  weight = 1
  name = "Thông Báo"
  url = "notice"

  [[Languages.vi.menu.main]]
  parent = "Khác"
  weight = 2
  name = "Tư Vấn"
  url = "consultancy"

  [[Languages.vi.menu.main]]
  parent = "Khác"
  weight = 3
  name = "Học Bổng"
  url = "scholarship"

#  [[Languages.vi.menu.main]]
#  parent = "Khác"
#  weight = 4
#  name = "Thư Viện"
#  url = "library"

  [[Languages.vi.menu.main]]
  parent = "Khác"
  weight = 5
  name = "Đối Tác"
  url = "partner"

  [[Languages.vi.menu.main]]
  parent = "Khác"
  weight = 6
  name = "Tuyển Dụng"
  url = "recruit"


# [[Languages.vi.menu.main]]
# name = "blog"
# url = "blog"
# weight = 4


#
# [[Languages.vi.menu.main]]
# name = "Liên Hệ"
# url = "contact"
# weight = 8


# footer menu

[[Languages.vi.menu.footer]]
name = "Nhân Sự"
url = "team"

[[Languages.vi.menu.footer]]
name = "Bảng Tin"
url = "notice"

[[Languages.vi.menu.footer]]
name = "Sự Kiện"
url = "event"

[[Languages.vi.menu.footer]]
name = "Học Bổng"
url = "scholarship"

[[Languages.vi.menu.footer]]
name = "Nghiên Cứu"
url = "research"
