######################## default configuration ####################
baseURL = "https://iscmueh.github.io/"
title = "Institute of Smart City & Management"
#theme = "iscmueh.github.io"
#themesDir = ".."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "iscmueh" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logoiscm.png"
# Meta data
description = "This is meta description"
author = "ISCM"
# contact info
address = "232/6 Võ Thị Sáu, P. Võ Thị Sáu, Quận 3"
mobile = "028.39309589 - 028.39309269"
email = "iscm@ueh.edu.vn"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "10.782734"
map_longitude = "106.685605"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 by [ISCM](https://iscm.ueh.edu.vn)"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 1

[[Languages.en.menu.main]]
name = "course"
url = "course"
weight = 2

[[Languages.en.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "team"
  url = "team"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "event"
  url = "event"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "scholarship"
  url = "scholarship"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research"

[[Languages.en.menu.main]]
weight = 4
name = "Resources"
hasChildren = true

    [[Languages.en.menu.main]]
    parent = "Pages"
    name = "team"
    url = "team"

    [[Languages.en.menu.main]]
    parent = "Pages"
    name = "notice"
    url = "notice"

    [[Languages.en.menu.main]]
    parent = "Pages"
    name = "event"
    url = "event"

    [[Languages.en.menu.main]]
    parent = "Pages"
    name = "scholarship"
    url = "scholarship"

    [[Languages.en.menu.main]]
    parent = "Pages"
    name = "research"
    url = "research"

#[[Languages.en.menu.main]]
#name = "blog"
#url = "blog"
#weight = 4
[[Languages.en.menu.main]]
name = "StudioLAB"
url = "studiolab"
weight = 5

[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 6


# footer menu

[[Languages.en.menu.footer]]
name = "team"
url = "team"

[[Languages.en.menu.footer]]
name = "notice"
url = "notice"

[[Languages.en.menu.footer]]
name = "event"
url = "event"

[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.en.menu.footer]]
name = "research"
url = "research"



################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2021 ISCM [themefisher](https://themefisher.com)"



################### French navigation ####################

# main menu
[[Languages.fr.menu.main]]
name = "À propos"
url = "about"
weight = 1

[[Languages.fr.menu.main]]
name = "Cours"
url = "course"
weight = 2

[[Languages.fr.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Évènement"
  url = "event"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Cursus"
  url = "scholarship"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research"

[[Languages.fr.menu.main]]
name = "blog"
url = "blog"
weight = 4

[[Languages.fr.menu.main]]
name = "Contact"
url = "contact"
weight = 5


# footer menu

[[Languages.fr.menu.footer]]
name = "teacher"
url = "teacher"

[[Languages.fr.menu.footer]]
name = "notice"
url = "notice"

[[Languages.fr.menu.footer]]
name = "event"
url = "event"

[[Languages.fr.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.fr.menu.footer]]
name = "research"
url = "research"
